overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=15.0.0-canary.0 <15.6.0-canary.61: '>=15.6.0-canary.61'
  next@>=15.5.1-canary.0 <15.5.10: '>=15.5.10'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
